### ISSUE TITLE
Feature: Use globbing for packages

### ISSUE THREAD

**Issue by toby-freemarket** [OctopusDeploy/push-package-action#173]
Hi! 
It would be cool if you could support globbing patterns for packages so you don't have to manually add the list of packages.
Like `packages/**/*.nupkg`

```yaml
steps:
  - uses: actions/checkout@v2
  - name: Install Octopus CLI 🐙
    uses: OctopusDeploy/install-octopus-cli-action@<version>
    with:
      version: latest
  - name: Push a package to Octopus Deploy 🐙
    uses: OctopusDeploy/push-package-action@<version>
    with:
      api_key: ${{ secrets.API_KEY }}
      packages: packages/**/*.nupkg
      server: ${{ secrets.SERVER }}
```
