### ISSUE TITLE
Pushing packages > 2GB will fail

### ISSUE THREAD

**Issue by benPearce1** [OctopusDeploy/push-package-action#347]
Due to a limitation in NodeJS, pushing a package file over 2GB in size will result in the following error:

`Error: Error: RangeError [ERR_FS_FILE_TOO_LARGE]: File size (2202366406) is greater than 2 GiB`

Workaround:

Add a step to your action to install the Octopus CLI

```
- name: Install Octopus CLI
   uses: OctopusDeploy/install-octopus-cli-action@v3.0.0
```

Then use the cli to push the package
```
- name: push package
   env:
     OCTOPUS_URL: ${{ secrets.OCTOPUS_URL }}
     OCTOPUS_API_KEY: ${{ secrets.OCTOPUS_API_KEY }}
   run: octopus package upload --space Default --package package.1.0.0.zip --no-prompt
```
